import { useEffect, useState } from "react";
import { Link } from "wouter";
import { AppShell } from "@/components/AppShell";
import { FormSelect } from "@/components/FormSelect";
import { useAccount } from "@/services/profile";
import type { LocaleKey } from "@/i18n/locales";

type Person = {id:string;email:string;state:string;district:string;profile:{name?:string;farm?:string;avatar?:string}};
type Message = {id:string;body:string;sender_role:string;created_at:number};
type AdminScan = {id:string;crop:string;created_at:number;hidden_at:number|null;image_path:string|null};
export function Conversation({userId}:{userId?:string}) {
  const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const url=`/api/messages${userId?`?userId=${encodeURIComponent(userId)}`:""}`;
  useEffect(()=>{let active=true;setMessages([]);const load=async()=>{try{const r=await fetch(url);if(!r.ok)throw new Error();const data=await r.json();if(active){setMessages(data);setError("");}}catch{if(active)setError("Messages could not be loaded.");}};void load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer);};},[url]);
  return <section className="rounded-xl border bg-card p-5"><h2 className="text-xl font-bold">Conversation with {userId?"farmer":"Wellfarm support"}</h2><div className="my-5 max-h-96 space-y-3 overflow-y-auto" aria-live="polite">{messages.length?messages.map(m=><div key={m.id} className={`max-w-[90%] rounded-xl p-3 ${m.sender_role==="admin"?"bg-primary text-primary-foreground":"ml-auto bg-secondary"}`}><p className="text-xs opacity-70">{m.sender_role==="admin"?"Admin":"Farmer"} · {new Date(m.created_at).toLocaleString()}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{m.body}</p></div>):<p className="text-sm text-muted-foreground">No messages yet.</p>}</div><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});if(!r.ok)throw new Error();setBody("");const latest=await fetch(url);if(latest.ok)setMessages(await latest.json());}catch{setError("Message could not be sent. Please retry.");}finally{setBusy(false);}}}><label className="text-sm">Message<textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} className="mt-2 w-full rounded-lg border bg-background p-3" /></label><button disabled={busy||!body.trim()} className="mt-3 rounded-lg bg-primary px-5 py-2 text-primary-foreground disabled:opacity-50">{busy?"Sending…":"Send message"}</button></form>{error&&<p role="alert" className="mt-3 text-destructive">{error}</p>}</section>;
}
export function AdminPage(props:{locale:LocaleKey;setLocale:(locale:LocaleKey)=>void}) {
  const {account}=useAccount();const [users,setUsers]=useState<Person[]>([]);const [selected,setSelected]=useState<Person|null>(null);const [scans,setScans]=useState<AdminScan[]>([]);const [state,setState]=useState("all");const [district,setDistrict]=useState("all");const [error,setError]=useState("");const [report,setReport]=useState<{candidates:{condition:string;confidence:number}[]}|null>(null);
  useEffect(()=>{if(account?.role!=="admin")return;let active=true;fetch("/api/admin/users").then(async r=>{if(!r.ok)throw new Error();const data=await r.json();if(active)setUsers(data);}).catch(()=>setError("Profiles could not be loaded."));return()=>{active=false;};},[account]);
  useEffect(()=>{let active=true;setScans([]);setReport(null);if(selected)fetch(`/api/admin/users/${selected.id}/scans`).then(async r=>{if(!r.ok)throw new Error();const data=await r.json();if(active)setScans(data);}).catch(()=>{if(active)setError("Scan history could not be loaded.");});return()=>{active=false;};},[selected]);
  if(account?.role!=="admin")return <main className="p-10"><h1 className="text-3xl">Admin access required</h1><Link href="/farmer">Return to your fieldbook</Link></main>;
  const filtered=users.filter(u=>(state==="all"||u.state===state)&&(district==="all"||u.district===district));
  return <AppShell role="insights" {...props}><h1 className="mb-3 text-4xl">Farmer administration</h1><p className="mb-6 text-sm text-muted-foreground">Profile locations are supplied by users. Removed scans are retained and labelled below.</p><div className="mb-6 grid gap-4 sm:grid-cols-2"><FormSelect aria-label="State" value={state} onChange={e=>{setState(e.target.value);setDistrict("all");}}><option value="all">All states</option>{[...new Set(users.map(u=>u.state).filter(Boolean))].sort().map(s=><option key={s}>{s}</option>)}</FormSelect><FormSelect aria-label="District" value={district} onChange={e=>setDistrict(e.target.value)}><option value="all">All districts</option>{[...new Set(users.filter(u=>state==="all"||u.state===state).map(u=>u.district).filter(Boolean))].sort().map(d=><option key={d}>{d}</option>)}</FormSelect></div>{error&&<p role="alert" className="mb-4 text-destructive">{error}</p>}<div className="grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="space-y-2">{filtered.map(u=><button key={u.id} onClick={()=>{setSelected(u);setError("");}} className={`block w-full rounded-xl border p-4 text-left ${selected?.id===u.id?"bg-secondary":"bg-card"}`}><strong className="block">{u.profile.name||u.email}</strong><span className="block break-all text-xs">{u.email}</span><span className="text-xs text-muted-foreground">{u.state||"State not provided"} · {u.district||"District not provided"}</span></button>)}{!filtered.length&&<p>No matching profiles.</p>}</aside><div className="space-y-5">{selected?<><section className="rounded-xl border bg-card p-5"><h2 className="text-2xl">{selected.profile.name||selected.email}</h2><p>{selected.profile.farm}</p>{selected.profile.avatar&&<img src={selected.profile.avatar} alt="Farmer profile" className="mt-3 h-20 w-20 rounded-full object-cover" />}</section><section className="rounded-xl border bg-card p-5"><h2 className="text-xl">Scan history ({scans.length})</h2>{scans.map(scan=><div key={scan.id} className="flex items-center gap-4 border-b py-4">{scan.image_path&&<img src={`/api/admin/scans/${scan.id}/image`} alt={scan.crop} className="h-16 w-16 rounded object-cover" />}<div><strong>{scan.crop}</strong><p className="text-xs">{new Date(scan.created_at).toLocaleString()}</p>{scan.hidden_at&&<p className="text-xs text-amber-800">Removed from farmer history · retained for admin</p>}</div><button className="ml-auto text-sm text-primary" onClick={async()=>{setReport(null);const r=await fetch(`/api/admin/scans/${scan.id}/analysis`);if(r.ok)setReport(await r.json());else setError("No saved report is available for this scan.");}}>View report</button></div>)}{report&&<div className="mt-4 rounded-lg bg-secondary p-4">{report.candidates.map(c=><p key={c.condition}>{c.condition} · {(c.confidence*100).toFixed(1)}%</p>)}</div>}</section><Conversation key={selected.id} userId={selected.id} /></>:<p>Select a profile to see scans and messages.</p>}</div></div></AppShell>;
}
export function MessagesPage(props:{locale:LocaleKey;setLocale:(locale:LocaleKey)=>void}) {return <AppShell role="farmer" {...props}><h1 className="mb-6 text-4xl">Messages</h1><Conversation /></AppShell>;}
