export type LocaleKey = "en" | "hi" | "mr" | "bn" | "te" | "ta" | "gu" | "kn" | "ml" | "pa" | "or" | "as";
export const languageNames: Record<LocaleKey, string> = { en: "English", hi: "हिन्दी", mr: "मराठी", bn: "বাংলা", te: "తెలుగు", ta: "தமிழ்", gu: "ગુજરાતી", kn: "ಕನ್ನಡ", ml: "മലയാളം", pa: "ਪੰਜਾਬੀ", or: "ଓଡ଼ିଆ", as: "অসমীয়া" };
type Copy = { nav: { how: string; farmers: string; officials: string; transparency: string; demo: string }; actions: { scan: string; open: string; back: string; next: string; save: string; retry: string; view: string }; common: { demo: string; live: string; prototype: string; simulated: string; high: string; moderate: string; low: string; verified: string; pending: string }; farmer: { hello: string; area: string; weather: string; recent: string; contribution: string; scanTitle: string; chooseCrop: string; symptoms: string; analyze: string; result: string; safety: string }; official: { title: string; overview: string; cases: string; referrals: string; report: string; intelligence: string; filters: string; updated: string }; lab: { title: string; assignments: string; verify: string; submit: string } };
const en: Copy = { nav: { how: "How it works", farmers: "For farmers", officials: "For officials", transparency: "Transparency", demo: "Guided demo" }, actions: { scan: "Scan a crop", open: "Open prototype", back: "Back", next: "Next step", save: "Save and continue", retry: "Try again", view: "View details" }, common: { demo: "Demo data", live: "Live", prototype: "Prototype model", simulated: "Simulated", high: "High", moderate: "Moderate", low: "Low", verified: "Verified", pending: "Pending review" }, farmer: { hello: "Good morning, S. Pradhan", area: "Cuttack district · approximate area", weather: "Field weather", recent: "Your recent scans", contribution: "Your scan helps the district see patterns sooner. Farm locations are aggregated before officials view them.", scanTitle: "Photograph an affected plant", chooseCrop: "Choose your crop", symptoms: "What are you seeing?", analyze: "Start analysis", result: "Early indication", safety: "This result is an early indication based on the submitted image. Check the affected plants and consult an agricultural expert before applying chemical treatment." }, official: { title: "Regional crop-health intelligence", overview: "National overview", cases: "Cases", referrals: "Referrals", report: "Monthly report", intelligence: "Outbreak intelligence", filters: "Filters", updated: "Updated 31 Mar 2025 · 16:20 IST" }, lab: { title: "Field verification desk", assignments: "Assignments", verify: "Verify case", submit: "Submit verification" } };
const regional: Record<Exclude<LocaleKey, "en">, Partial<Copy>> = {
  hi: { nav: { how: "यह कैसे काम करता है", farmers: "किसानों के लिए", officials: "अधिकारियों के लिए", transparency: "पारदर्शिता", demo: "निर्देशित डेमो" }, actions: { scan: "फसल स्कैन करें", open: "प्रोटोटाइप खोलें", next: "अगला चरण", back: "वापस", save: "सहेजें", retry: "पुनः प्रयास", view: "विवरण देखें" }, farmer: { hello: "सुप्रभात, एस. प्रधान", area: "कटक ज़िला · अनुमानित क्षेत्र", weather: "खेत का मौसम", recent: "आपके हाल के स्कैन", contribution: "आपका स्कैन ज़िले को पैटर्न जल्दी देखने में मदद करता है।", scanTitle: "प्रभावित पौधे की तस्वीर लें", chooseCrop: "अपनी फसल चुनें", symptoms: "आप क्या देख रहे हैं?", analyze: "विश्लेषण शुरू करें", result: "प्रारंभिक संकेत", safety: "यह परिणाम भेजी गई तस्वीर पर आधारित प्रारंभिक संकेत है। प्रभावित पौधों की जाँच करें और रासायनिक उपचार से पहले कृषि विशेषज्ञ से सलाह लें।" } },
  mr: { nav: { how: "हे कसे कार्य करते", farmers: "शेतकऱ्यांसाठी", officials: "अधिकाऱ्यांसाठी", transparency: "पारदर्शकता", demo: "मार्गदर्शित डेमो" } },
  bn: { nav: { how: "যেভাবে কাজ করে", farmers: "কৃষকদের জন্য", officials: "কর্মকর্তাদের জন্য", transparency: "স্বচ্ছতা", demo: "নির্দেশিত ডেমো" } },
  te: { nav: { how: "ఇది ఎలా పనిచేస్తుంది", farmers: "రైతుల కోసం", officials: "అధికారుల కోసం", transparency: "పారదర్శకత", demo: "గైడెడ్ డెమో" } },
  ta: { nav: { how: "இது எப்படி இயங்குகிறது", farmers: "விவசாயிகளுக்கு", officials: "அதிகாரிகளுக்கு", transparency: "வெளிப்படைத்தன்மை", demo: "வழிகாட்டும் டெமோ" } },
  gu: { nav: { how: "તે કેવી રીતે કામ કરે છે", farmers: "ખેડૂતો માટે", officials: "અધિકારીઓ માટે", transparency: "પારદર્શિતા", demo: "માર્ગદર્શિત ડેમો" } },
  kn: { nav: { how: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", farmers: "ರೈತರಿಗಾಗಿ", officials: "ಅಧಿಕಾರಿಗಳಿಗಾಗಿ", transparency: "ಪಾರದರ್ಶಕತೆ", demo: "ಮಾರ್ಗದರ್ಶಿತ ಡೆಮೊ" } },
  ml: { nav: { how: "എങ്ങനെ പ്രവർത്തിക്കുന്നു", farmers: "കർഷകർക്കായി", officials: "ഉദ്യോഗസ്ഥർക്കായി", transparency: "സുതാര്യത", demo: "ഗൈഡഡ് ഡെമോ" } },
  pa: { nav: { how: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ", farmers: "ਕਿਸਾਨਾਂ ਲਈ", officials: "ਅਧਿਕਾਰੀਆਂ ਲਈ", transparency: "ਪਾਰਦਰਸ਼ਤਾ", demo: "ਗਾਈਡਡ ਡੈਮੋ" } },
  or: { nav: { how: "ଏହା କିପରି କାମ କରେ", farmers: "ଚାଷୀଙ୍କ ପାଇଁ", officials: "ଅଧିକାରୀଙ୍କ ପାଇଁ", transparency: "ସ୍ୱଚ୍ଛତା", demo: "ଗାଇଡେଡ୍ ଡେମୋ" } },
  as: { nav: { how: "ই কেনেকৈ কাম কৰে", farmers: "কৃষকৰ বাবে", officials: "বিষয়াৰ বাবে", transparency: "স্বচ্ছতা", demo: "নিৰ্দেশিত ডেমো" } },
};
function merge(base: Copy, extra: Partial<Copy>): Copy {
  return { ...base, ...extra, nav: { ...base.nav, ...extra.nav }, actions: { ...base.actions, ...extra.actions }, common: { ...base.common, ...extra.common }, farmer: { ...base.farmer, ...extra.farmer }, official: { ...base.official, ...extra.official }, lab: { ...base.lab, ...extra.lab } };
}
export const locales: Record<LocaleKey, Copy> = { en, ...Object.fromEntries(Object.entries(regional).map(([key, value]) => [key, merge(en, value)])) } as Record<LocaleKey, Copy>;